version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql_prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "*Ols2024"
      MYSQL_DATABASE: "linha_producao"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build:
      context: ./auth_jwt
      dockerfile: Dockerfile
    container_name: backend_bmw
    restart: always
    env_file:
      - ./auth_jwt/.env.docker
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./front
    container_name: frontend_bmw
    restart: always
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://3.236.52.36:3000"   
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    depends_on:
      - backend

volumes:
  mysql_data:
